/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafemanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author M. A. MUKTADEER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String userEmail;

    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        this.userEmail = userEmail;
        if (!userEmail.equals("admin@gmail.com")) {
            btnAddProduct.setVisible(false);
            btnCategory.setVisible(false);
            btnProductDetailes.setVisible(false);
            btnVerifyUsers.setVisible(false);
        }
    }

    void windo() {
        ViewEditAdDeleteProduct nn = new ViewEditAdDeleteProduct();
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogut = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnViewBillAndOrd = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnProductDetailes = new javax.swing.JButton();
        btnVerifyUsers = new javax.swing.JButton();
        btnChngeSecurityQues = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cafemanagementsystem/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Home.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1212, 10, 30, -1));

        btnLogut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogut.setForeground(new java.awt.Color(0, 0, 0));
        btnLogut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btnLogut.setText(bundle.getString("Home.btnLogut.text")); // NOI18N
        btnLogut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 33));

        btnPlaceOrder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/place order.png"))); // NOI18N
        btnPlaceOrder.setText(bundle.getString("Home.btnPlaceOrder.text")); // NOI18N
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 32));

        btnCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCategory.setForeground(new java.awt.Color(0, 0, 0));
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/category.png"))); // NOI18N
        btnCategory.setText(bundle.getString("Home.btnCategory.text")); // NOI18N
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, -1, 32));

        btnAddProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new product.png"))); // NOI18N
        btnAddProduct.setText(bundle.getString("Home.btnAddProduct.text")); // NOI18N
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, -1, 30));

        btnViewBillAndOrd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewBillAndOrd.setForeground(new java.awt.Color(0, 0, 0));
        btnViewBillAndOrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View Bills & Order Placed Details.png"))); // NOI18N
        btnViewBillAndOrd.setText(bundle.getString("Home.btnViewBillAndOrd.text")); // NOI18N
        btnViewBillAndOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillAndOrdActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewBillAndOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 29));

        btnChangePass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change Password.png"))); // NOI18N
        btnChangePass.setText(bundle.getString("Home.btnChangePass.text")); // NOI18N
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, 31));

        btnProductDetailes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProductDetailes.setForeground(new java.awt.Color(0, 0, 0));
        btnProductDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view edit delete product.png"))); // NOI18N
        btnProductDetailes.setText(bundle.getString("Home.btnProductDetailes.text")); // NOI18N
        btnProductDetailes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductDetailesActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, -1, 31));

        btnVerifyUsers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVerifyUsers.setForeground(new java.awt.Color(0, 0, 0));
        btnVerifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/verify users.png"))); // NOI18N
        btnVerifyUsers.setText(bundle.getString("Home.btnVerifyUsers.text")); // NOI18N
        btnVerifyUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, -1, 31));

        btnChngeSecurityQues.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChngeSecurityQues.setForeground(new java.awt.Color(0, 0, 0));
        btnChngeSecurityQues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change Security Question.png"))); // NOI18N
        btnChngeSecurityQues.setText(bundle.getString("Home.btnChngeSecurityQues.text")); // NOI18N
        btnChngeSecurityQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChngeSecurityQuesActionPerformed(evt);
            }
        });
        jPanel1.add(btnChngeSecurityQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-background-image.png"))); // NOI18N
        jLabel2.setText(bundle.getString("Home.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Do you want to Exit the application?", "message", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(a);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnChngeSecurityQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChngeSecurityQuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChngeSecurityQuesActionPerformed

    private void btnVerifyUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUsersActionPerformed
        // TODO add your handling code here:
        VerifyUser nn = new VerifyUser(userEmail);
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(true);
    }//GEN-LAST:event_btnVerifyUsersActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        ChangePassword nn = new ChangePassword(userEmail);
        nn.setBounds(310, 150, 800, 449);
        nn.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
//        new manageCategory().setDefaultCloseOperation(1);
        manageCategory nn = new manageCategory(userEmail);
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(true);
//        nn.setOpacity(0.8f);

    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnLogutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Do you want to Log Out?", "message", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogutActionPerformed

    private void btnProductDetailesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductDetailesActionPerformed
        // TODO add your handling code here:
        ViewEditAdDeleteProduct nn = new ViewEditAdDeleteProduct(userEmail);
        nn.setVisible(rootPaneCheckingEnabled);
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(true);
    }//GEN-LAST:event_btnProductDetailesActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        NewProduct nn = new NewProduct(userEmail);        
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        PlaceOrder nn = new PlaceOrder(userEmail);
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnViewBillAndOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillAndOrdActionPerformed
        // TODO add your handling code here:
        ViewBillAndOrderDetails nn = new ViewBillAndOrderDetails(userEmail);
        nn.setBounds(130, 120, 1100, 540);
        nn.setVisible(true);
    }//GEN-LAST:event_btnViewBillAndOrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnChngeSecurityQues;
    private javax.swing.JButton btnLogut;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnProductDetailes;
    private javax.swing.JButton btnVerifyUsers;
    private javax.swing.JButton btnViewBillAndOrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
