/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Dao.BillDao;
import Dao.CategoryDao;
import Dao.ProductDao;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import model.Bill;
import model.Category;
import model.Product;

/**
 *
 * @author M. A. MUKTADEER
 */
public class PlaceOrder extends javax.swing.JFrame {

    public static int billId;

    /**
     * Creates new form ViewEditAdDeleteProduct
     */
    public PlaceOrder() {
        initComponents();
    }
    String email;

    public PlaceOrder(String userEmail) {
        initComponents();
        email = userEmail;
        category();
        btnAddCart.setEnabled(false);
        btnPrintInvoise.setEnabled(false);
    }

    void clear() {
        txtProductName.setText("");
        txtProductPrice.setText("");
        txtQuantity.setText("");
        txtTotal.setText("");
        btnAddCart.setEnabled(false);
    }

    void validbtnPrint() {
        if (!txtCName.getText().equals("") && !txtEmail.getText().equals("") && !txtMobailNumber.getText().equals("")) {
            btnPrintInvoise.setEnabled(true);
        } else {
            btnPrintInvoise.setEnabled(false);
        }
    }

    void validAddCart() {
        if (!txtProductName.getText().equals("") && !txtProductPrice.getText().equals("") && !txtTotal.getText().equals("")) {
            btnAddCart.setEnabled(true);
        } else {
            btnAddCart.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtProductSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        combCategory = new javax.swing.JComboBox<>();
        txtMobailNumber = new javax.swing.JTextField();
        btnAddCart = new javax.swing.JButton();
        txtCName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JLabel();
        btnPrintInvoise = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cafemanagementsystem/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("PlaceOrder.jLabel1.text")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/place order.png"))); // NOI18N
        jLabel2.setText(bundle.getString("PlaceOrder.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(bundle.getString("PlaceOrder.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("PlaceOrder.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(bundle.getString("PlaceOrder.jLabel7.text")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(bundle.getString("PlaceOrder.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(bundle.getString("PlaceOrder.jLabel8.text")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(bundle.getString("PlaceOrder.jLabel10.text")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(bundle.getString("PlaceOrder.jLabel11.text")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtProductSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtProductSearch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtProductSearch.setForeground(new java.awt.Color(0, 102, 102));
        txtProductSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductSearch.setText(bundle.getString("PlaceOrder.txtProductSearch.text")); // NOI18N
        txtProductSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtProductSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtProductSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 170, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(bundle.getString("PlaceOrder.jLabel12.text")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        txtProductPrice.setEditable(false);
        txtProductPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtProductPrice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtProductPrice.setForeground(new java.awt.Color(0, 102, 102));
        txtProductPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductPrice.setText(bundle.getString("PlaceOrder.txtProductPrice.text")); // NOI18N
        txtProductPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 110, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(bundle.getString("PlaceOrder.jLabel14.text")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, 30));

        txtQuantity.setBackground(new java.awt.Color(204, 204, 204));
        txtQuantity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(0, 102, 102));
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantity.setText(bundle.getString("PlaceOrder.txtQuantity.text")); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 80, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(bundle.getString("PlaceOrder.jLabel13.text")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 154, -1, 20));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtTotal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 102, 102));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText(bundle.getString("PlaceOrder.txtTotal.text")); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 110, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(bundle.getString("PlaceOrder.jLabel15.text")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, 30));

        txtProductName.setEditable(false);
        txtProductName.setBackground(new java.awt.Color(204, 204, 204));
        txtProductName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtProductName.setForeground(new java.awt.Color(0, 102, 102));
        txtProductName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductName.setText(bundle.getString("PlaceOrder.txtProductName.text")); // NOI18N
        txtProductName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 140, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 102, 102));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText(bundle.getString("PlaceOrder.txtEmail.text")); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobailNumberKeyReleased1(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 30));

        txtId.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setText(bundle.getString("PlaceOrder.txtId.text")); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnClear.setText(bundle.getString("PlaceOrder.btnClear.text")); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        combCategory.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        combCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combCategoryItemStateChanged(evt);
            }
        });
        getContentPane().add(combCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, -1));

        txtMobailNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMobailNumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtMobailNumber.setForeground(new java.awt.Color(0, 102, 102));
        txtMobailNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMobailNumber.setText(bundle.getString("PlaceOrder.txtMobailNumber.text")); // NOI18N
        txtMobailNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtMobailNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtMobailNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, 30));

        btnAddCart.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnAddCart.setText(bundle.getString("PlaceOrder.btnAddCart.text")); // NOI18N
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });
        btnAddCart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobailNumberKeyReleased(evt);
            }
        });
        getContentPane().add(btnAddCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 110, 110, -1));

        txtCName.setBackground(new java.awt.Color(204, 204, 204));
        txtCName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtCName.setForeground(new java.awt.Color(0, 102, 102));
        txtCName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCName.setText(bundle.getString("PlaceOrder.txtCName.text")); // NOI18N
        txtCName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(bundle.getString("PlaceOrder.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, 30));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name"
            }
        ));
        tblProduct.setOpaque(false);
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("PlaceOrder.ttt.columnModel.title0")); // NOI18N
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 180, 400));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("PlaceOrder.tblCart.columnModel.title0")); // NOI18N
            tblCart.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("PlaceOrder.tblCart.columnModel.title1")); // NOI18N
            tblCart.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("PlaceOrder.tblCart.columnModel.title2")); // NOI18N
            tblCart.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("PlaceOrder.tblCart.columnModel.title3")); // NOI18N
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, 250));

        jLabel16.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText(bundle.getString("PlaceOrder.jLabel16.text")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        txtGrandTotal.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        txtGrandTotal.setForeground(new java.awt.Color(0, 51, 153));
        txtGrandTotal.setText(bundle.getString("PlaceOrder.txtGrandTotal.text")); // NOI18N
        getContentPane().add(txtGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        btnPrintInvoise.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPrintInvoise.setText(bundle.getString("PlaceOrder.btnPrintInvoise.text")); // NOI18N
        btnPrintInvoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintInvoiseActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrintInvoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/full-page-background.PNG"))); // NOI18N
        jLabel9.setText(bundle.getString("PlaceOrder.jLabel9.text")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void category() {
        ArrayList<Category> list = CategoryDao.getllRecords();
        Iterator<Category> itr = list.iterator();
        combCategory.removeAllItems();
        combCategory.addItem(" ");
        while (itr.hasNext()) {
            Category category = itr.next();
            combCategory.addItem(category.getCategory());
        }
    }


    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void combCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combCategoryItemStateChanged
        // TODO add your handling code here:
        String category = combCategory.getSelectedItem().toString();
        ArrayList<Product> list = ProductDao.getAllRecords();
        Iterator<Product> itr = list.iterator();
        DefaultTableModel dtm = (DefaultTableModel) tblProduct.getModel();
        dtm.setRowCount(0);
        while (itr.hasNext()) {
            Product product = itr.next();
            if (product.getCategory().equals(category)) {
                dtm.addRow(new Object[]{product.getName()});
//                txtProductName.setText(product.getName());
//                txtProductPrice.setText(product.getPrice());
            }
        }

    }//GEN-LAST:event_combCategoryItemStateChanged

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int index = tblProduct.getSelectedRow();
        TableModel model = tblProduct.getModel();
        String name = model.getValueAt(index, 0).toString();
        String category = combCategory.getSelectedItem().toString();
//        txtProductName.setText(name);
        Product product = ProductDao.getPrductByName(name);
        txtProductName.setText(product.getName());
        txtProductPrice.setText(product.getPrice());
    }//GEN-LAST:event_tblProductMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(BillDao.getId());
        txtId.setText(String.valueOf(billId));
    }//GEN-LAST:event_formComponentShown

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtProductSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductSearchKeyReleased
        // TODO add your handling code here:
        String name = txtProductSearch.getText();
        String category = combCategory.getSelectedItem().toString();

        ArrayList<Product> list = ProductDao.getSearchProductName(name, category);
        Iterator<Product> itr = list.iterator();
        DefaultTableModel dtm = (DefaultTableModel) tblProduct.getModel();
        dtm.setRowCount(0);
        while (itr.hasNext()) {
            Product product = itr.next();
            dtm.addRow(new Object[]{product.getName()});
        }
    }//GEN-LAST:event_txtProductSearchKeyReleased

    private void txtMobailNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobailNumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobailNumberKeyReleased

    double grandTotal = 0;
    double total = 0;
    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
        // TODO add your handling code here:
        String name = txtProductName.getText();
        String price = txtProductPrice.getText();
        String quantity = txtQuantity.getText();
        String totalsString = txtTotal.getText();
        DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
        dtm.addRow(new Object[]{name, price, quantity, totalsString});
        total = Double.parseDouble(totalsString);
        grandTotal = grandTotal + total;
        txtGrandTotal.setText(String.valueOf(grandTotal));
        clear();
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void txtMobailNumberKeyReleased1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobailNumberKeyReleased1
        // TODO add your handling code here:
        validbtnPrint();
    }//GEN-LAST:event_txtMobailNumberKeyReleased1

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        double price = Double.parseDouble(txtProductPrice.getText());
        int quentity = Integer.parseInt(txtQuantity.getText());
        double total = price * quentity;
        txtTotal.setText(String.valueOf(total));
        validAddCart();
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void btnPrintInvoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintInvoiseActionPerformed
        // TODO add your handling code here:
        if (!email.equals("")) {
            String id = txtId.getText();
            String customarName = txtCName.getText();
            String customarPhone = txtMobailNumber.getText();
            String customarEmail = txtEmail.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
            Date dt = new Date();
            String todayDate = dateFormat.format(dt);
            String total = txtGrandTotal.getText();
            String createdBy = email;
            Bill bill = new Bill();
            bill.setId(Integer.parseInt(id));
            bill.setName(customarName);
            bill.setMobailNumber(customarPhone);
            bill.setEmail(customarEmail);
            bill.setDate(todayDate);
            bill.setTotal(total);
            bill.setCreateBy(createdBy);
            BillDao.saveBill(bill);

            ////////////creae bill
            String path = "D:\\java 1st project bill";
            Document doc = new Document() {
              
                public int getLength() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

             
                public void addDocumentListener(DocumentListener listener) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void removeDocumentListener(DocumentListener listener) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void addUndoableEditListener(UndoableEditListener listener) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void removeUndoableEditListener(UndoableEditListener listener) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Object getProperty(Object key) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void putProperty(Object key, Object value) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void remove(int offs, int len) throws BadLocationException {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void insertString(int offset, String str, AttributeSet a) throws BadLocationException {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public String getText(int offset, int length) throws BadLocationException {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void getText(int offset, int length, Segment txt) throws BadLocationException {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Position getStartPosition() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Position getEndPosition() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Position createPosition(int offs) throws BadLocationException {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Element[] getRootElements() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public Element getDefaultRootElement() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                public void render(Runnable r) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            };
            try {
                PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
                doc.open();
                Paragraph cafeName = new Paragraph("                                                      Cafe Manegment System");
                doc.add(cafeName);
                Paragraph starLine = new Paragraph("**************************************************************************************************************");
                doc.add(starLine);
                Paragraph paragraph3 = new Paragraph("Bill Id:" + id + "\nCustmar Name:  " + customarName + "                                                                        Total Paid: " + grandTotal);
                doc.add(paragraph3);
                doc.add(starLine);
                PdfPTable tb1 = new PdfPTable(4);
                tb1.addCell("Name");
                tb1.addCell("Price");
                tb1.addCell("Quentity");
                tb1.addCell("Total");
                for (int i = 0; i < tblCart.getRowCount(); i++) {
                    String m = tblCart.getValueAt(i, 0).toString();
                    String n = tblCart.getValueAt(i, 1).toString();
                    String o = tblCart.getValueAt(i, 2).toString();
                    String p = tblCart.getValueAt(i, 3).toString();
                    tb1.addCell(m);
                    tb1.addCell(n);
                    tb1.addCell(o);
                    tb1.addCell(p);
                }
                doc.add(tb1);
                doc.add(starLine);
                Paragraph thanksMs = new Paragraph("Thank you. Please Came Again...");
                doc.add(thanksMs);
                OpenPdf.openById(id);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            doc.close();
            setVisible(false);
            new PlaceOrder(createdBy).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Login Email Is not Found!");
        }
    }//GEN-LAST:event_btnPrintInvoiseActionPerformed

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        // TODO add your handling code here:
        int index = tblCart.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this, "Do you wat to remove this product", "Yes", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = tblCart.getModel();
            String total = model.getValueAt(index, 3).toString();
            double grandTotal = Double.parseDouble(txtGrandTotal.getText());
            double newGrandTotal = grandTotal - Double.parseDouble(total);
            txtGrandTotal.setText(String.valueOf(newGrandTotal));
            ((DefaultTableModel) tblCart.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_tblCartMouseClicked

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        String emailPattern = "^[a-zA-Z._0-9]{0,50}+[@]+[a-zA-Z]+[.]+[a-zA-z]+$";
        String validMobile = "^[0-9]{11,15}$";
        String validName = "^[a-zA-z]{0,30}$";
        String mobile = txtMobailNumber.getText();
        if (!txtCName.getText().equals("")) {
            if (!txtCName.getText().matches(validName)) {
                JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Number is Not Allowed.</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtCName.requestFocus();
            } else if (!mobile.equals("")) {
                if (!mobile.matches(validMobile)) {
                    JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Mobile Number Must Be Atlist 11 Digit Number.</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
                    txtMobailNumber.requestFocus();
                } else if (!txtEmail.getText().equals("")) {
                    if (!txtEmail.getText().matches(emailPattern)) {
                        JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Invalid Email!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
                        txtEmail.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Email Can't Be Empty!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
                    txtEmail.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Mobile Number Can't Be Empty!</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtMobailNumber.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "<html><b style=\"color:red\">Name Is Needed.</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE);
            txtCName.requestFocus();
        }

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtCNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNameKeyReleased
        // TODO add your handling code here:
        validbtnPrint();
    }//GEN-LAST:event_txtCNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrintInvoise;
    private javax.swing.JComboBox<String> combCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtGrandTotal;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtMobailNumber;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductSearch;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
