/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import DAO.userDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.User;

/**
 *
 * @author M. A. MUKTADEER
 */
public class VerifyUser extends javax.swing.JFrame {
    String userEmail;

    /**
     * Creates new form ViewEditAdDeleteProduct
     */
    public VerifyUser() {
        initComponents();
    }
    
    public VerifyUser(String email) {
        initComponents();
        userEmail=email;
    }
    

    void clear() {
        setVisible(false);
        new VerifyUser().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUaerDetails = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        combStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cafemanagementsystem/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("VerifyUser.jLabel1.text")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/verify users.png"))); // NOI18N
        jLabel2.setText(bundle.getString("VerifyUser.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        tblUaerDetails.setBackground(new java.awt.Color(204, 204, 204));
        tblUaerDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblUaerDetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblUaerDetails.setForeground(new java.awt.Color(0, 102, 102));
        tblUaerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Mobile Number", "Address", "Sequrity Question", "Status"
            }
        ));
        tblUaerDetails.setOpaque(false);
        tblUaerDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUaerDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUaerDetails);
        if (tblUaerDetails.getColumnModel().getColumnCount() > 0) {
            tblUaerDetails.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title0")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title1")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title2")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title3")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title4")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title5")); // NOI18N
            tblUaerDetails.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("VerifyUser.tblUaerDetails.columnModel.title6")); // NOI18N
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 990, 420));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText(bundle.getString("VerifyUser.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 590, 40));

        combStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all", "true", "false" }));
        combStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combStatusItemStateChanged(evt);
            }
        });
        getContentPane().add(combStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(bundle.getString("VerifyUser.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 102, 102));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText(bundle.getString("VerifyUser.txtEmail.text")); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 210, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jLabel6.setText(bundle.getString("VerifyUser.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/full-page-background.PNG"))); // NOI18N
        jLabel9.setText(bundle.getString("VerifyUser.jLabel9.text")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblUaerDetails.getModel();
        ArrayList<User> list = userDao.getAllUser("","");
        Iterator<User> itr = list.iterator();
        while (itr.hasNext()) {
            User user = itr.next();
            if (!user.getEmail().equals("admin@gmail.com")) {
                dtm.addRow(new Object[]{user.getId(), user.getName(), user.getEmail(), user.getMobileNumber(), user.getAddress(), user.getSecuryQuestion(), user.getStatus()});
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void tblUaerDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUaerDetailsMouseClicked
        // TODO add your handling code here:
        TableModel model = tblUaerDetails.getModel();
        int index = tblUaerDetails.getSelectedRow();
        String email = model.getValueAt(index, 2).toString();
        String status = model.getValueAt(index, 6).toString();
        if (status.equals("true")) {
            status = "false";
        } else {
            status = "true";
        }
        int a = JOptionPane.showConfirmDialog(this, "Do you want to change Status for "+email+"?","Yes",JOptionPane.YES_NO_OPTION);
        if(a==0){
            userDao.stasusUpdate(email, status);
            setVisible(false);
            new VerifyUser().setVisible(true);
        }
    }//GEN-LAST:event_tblUaerDetailsMouseClicked

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        ArrayList<User> arrayList = userDao.getAllUser(txtEmail.getText(), combStatus.getSelectedItem().toString());
        Iterator<User> itr = arrayList.iterator();
        DefaultTableModel dtm = (DefaultTableModel) tblUaerDetails.getModel();
        dtm.setRowCount(0);
        while (itr.hasNext()) {
            User user = itr.next();
            if (!user.getEmail().equals("admin@gmail.com")) {
                dtm.addRow(new Object[]{user.getId(), user.getName(), user.getEmail(), user.getMobileNumber(), user.getAddress(), user.getSecuryQuestion(), user.getStatus()});
            }
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void combStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combStatusItemStateChanged
        // TODO add your handling code here:
        if (combStatus.getSelectedItem().equals("false")) {
            String email = "admin@gmail.com";
            String status = combStatus.getSelectedItem().toString();
            DefaultTableModel dtm = (DefaultTableModel) tblUaerDetails.getModel();
            dtm.setRowCount(0);///////////
            ArrayList<User> list = userDao.getAllUsers(email, status);
            Iterator<User> itr = list.iterator();
            while (itr.hasNext()) {
                User user = itr.next();
                if (!user.getEmail().equals("admin@gmail.com")) {
                    dtm.addRow(new Object[]{user.getId(), user.getName(), user.getEmail(), user.getMobileNumber(), user.getAddress(), user.getSecuryQuestion(), user.getStatus()});
                }
            }
        } else if (combStatus.getSelectedItem().equals("true")) {
            String email = "admin@gmail.com";
            String status = combStatus.getSelectedItem().toString();
            DefaultTableModel dtm = (DefaultTableModel) tblUaerDetails.getModel();
            dtm.setRowCount(0);
            ArrayList<User> list = userDao.getAllUsers(email, status);
            Iterator<User> itr = list.iterator();
            while (itr.hasNext()) {
                User user = itr.next();
                if (!user.getEmail().equals(email)) {
                    dtm.addRow(new Object[]{user.getId(), user.getName(), user.getEmail(), user.getMobileNumber(), user.getAddress(), user.getSecuryQuestion(), user.getStatus()});
                }
            }
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblUaerDetails.getModel();
            dtm.setRowCount(0);
            ArrayList<User> list = userDao.getAllUser("","");
            Iterator<User> itr = list.iterator();
            while (itr.hasNext()) {
                User user = itr.next();
                if (!user.getEmail().equals("admin@gmail.com")) {
                    dtm.addRow(new Object[]{user.getId(), user.getName(), user.getEmail(), user.getMobileNumber(), user.getAddress(), user.getSecuryQuestion(), user.getStatus()});
                }
            }
        }
    }//GEN-LAST:event_combStatusItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUaerDetails;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
