/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Dao.BillDao;
import Dao.CategoryDao;
import common.OpenPdf;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;

/**
 *
 * @author M. A. MUKTADEER
 */
public class ViewBillAndOrderDetails extends javax.swing.JFrame {

    public static int billId;
    String email;
    String order;
    String name;

    /**
     * Creates new form ViewEditAdDeleteProduct
     */
    public ViewBillAndOrderDetails() {
        initComponents();
    }
    

    public ViewBillAndOrderDetails(String userEmail) {
        initComponents();
        email = userEmail;
        getDate();
    }

    void clear() {

    }

    public void getDate() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
        Date dt = new Date();
        String todayDate = dateFormat.format(dt);
        txtDt.setText(todayDate);
    }

    public void setBillInTable() {
        String comString = (String) comb.getSelectedItem();
        name = txtDt.getText();
        if (!email.equals("admin@gmail.com")) {
            email = email;
            if (comString.equals("Ascending")) {
                order = "asc";
            } else if (comString.equals("Descending")) {
                order = "desc";
            }
            ArrayList<Bill> bill = BillDao.getBillInOrder(email, order);
            Iterator<Bill> itr = bill.iterator();
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.setRowCount(0);
            while (itr.hasNext()) {
                Bill billObj = itr.next();
                dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobailNumber(), billObj.getEmail(), billObj.getDate(), billObj.getTotal()});
            }
        } else {
            if (comString.equals("Ascending")) {
                order = "asc";
            } else if (comString.equals("Descending")) {
                order = "desc";
            }
            ArrayList<Bill> bill = BillDao.getBillInOrderAdmin(order);
            Iterator<Bill> itr = bill.iterator();
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.setRowCount(0);
            while (itr.hasNext()) {
                Bill billObj = itr.next();
                dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobailNumber(), billObj.getEmail(), billObj.getDate(), billObj.getTotal(), billObj.getCreateBy()});
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comb = new javax.swing.JComboBox<>();
        txtDt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cafemanagementsystem/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("ViewBillAndOrderDetails.jLabel1.text")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/place order.png"))); // NOI18N
        jLabel2.setText(bundle.getString("ViewBillAndOrderDetails.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(bundle.getString("ViewBillAndOrderDetails.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(bundle.getString("ViewBillAndOrderDetails.jLabel13.text")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 30));

        comb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        comb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combItemStateChanged(evt);
            }
        });
        getContentPane().add(comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 110, -1));

        txtDt.setBackground(new java.awt.Color(204, 204, 204));
        txtDt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDt.setForeground(new java.awt.Color(0, 102, 102));
        txtDt.setText(bundle.getString("ViewBillAndOrderDetails.txtDt.text")); // NOI18N
        txtDt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDtKeyReleased(evt);
            }
        });
        getContentPane().add(txtDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 180, -1));

        tblCart.setBackground(new java.awt.Color(204, 204, 204));
        tblCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCart.setForeground(new java.awt.Color(0, 102, 102));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobail Number", "Email", "Date", "Total", "CreateBy"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title0")); // NOI18N
            tblCart.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title1")); // NOI18N
            tblCart.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title2")); // NOI18N
            tblCart.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title3")); // NOI18N
            tblCart.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title4")); // NOI18N
            tblCart.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title5")); // NOI18N
            tblCart.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("ViewBillAndOrderDetails.tblCart.columnModel.title6")); // NOI18N
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1000, 370));

        jLabel16.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText(bundle.getString("ViewBillAndOrderDetails.jLabel16.text")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/full-page-background.PNG"))); // NOI18N
        jLabel9.setText(bundle.getString("ViewBillAndOrderDetails.jLabel9.text")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        // TODO add your handling code here:
        int index = tblCart.getSelectedRow();
        TableModel model = tblCart.getModel();
        String id = model.getValueAt(index, 0).toString();
        OpenPdf.openById(id);
        
    }//GEN-LAST:event_tblCartMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        setBillInTable();
    }//GEN-LAST:event_formComponentShown

    private void combItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combItemStateChanged
        // TODO add your handling code here:
        setBillInTable();
    }//GEN-LAST:event_combItemStateChanged

    private void txtDtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDtKeyReleased
        // TODO add your handling code here:
        String comString = (String) comb.getSelectedItem();
        name = txtDt.getText();
        if (!email.equals("admin@gmail.com")) {
            email = email;
            if (comString.equals("Ascending")) {
                order = "asc";
            } else if (comString.equals("Descending")) {
                order = "desc";
            }
            ArrayList<Bill> bill = BillDao.getBillInOrder(email, order, name);
            Iterator<Bill> itr = bill.iterator();
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.setRowCount(0);
            while (itr.hasNext()) {
                Bill billObj = itr.next();
                dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobailNumber(), billObj.getEmail(), billObj.getDate(), billObj.getTotal()});
            }
        } else {
            if (comString.equals("Ascending")) {
                order = "asc";
            } else if (comString.equals("Descending")) {
                order = "desc";
            }
            ArrayList<Bill> bill = BillDao.getBillInOrderAdmin(order, name);
            Iterator<Bill> itr = bill.iterator();
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.setRowCount(0);
            while (itr.hasNext()) {
                Bill billObj = itr.next();
                dtm.addRow(new Object[]{billObj.getId(), billObj.getName(), billObj.getMobailNumber(), billObj.getEmail(), billObj.getDate(), billObj.getTotal(), billObj.getCreateBy()});
            }
        }
    }//GEN-LAST:event_txtDtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBillAndOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBillAndOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBillAndOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBillAndOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillAndOrderDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtDt;
    // End of variables declaration//GEN-END:variables
}
